version: '3'
services:
  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    hostname: db
    volumes:
      - ./sample/db:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bundle exec unicorn -c config/unicorn.rb -E production -l 3000
    volumes:
      - .:/opt/application/current
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: 'production'
      RACK_ENV: 'production'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_USER: 'root'
      DB_PASSWORD: 'password'
      DB_NAME: 'sample'
      REGION: ${REGION}
      BUCKET_NAME: ${BUCKET_NAME}
      OBJECT_KEY: ${OBJECT_KEY}
      EXPIRE_TIME: ${EXPIRE_TIME}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
    links:
      - db
