version: "3"
services:
  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    hostname: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: vehicle_management
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/opt/application/current
      - /opt/application/current/node_modules
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: "production"
      RACK_ENV: "production"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "password"
      DB_NAME: "vehicle_management"
      WEB_DOMAIN: ${WEB_DOMAIN:-invalid}
      EMAIL_DOMAIN: ${EMAIL_DOMAIN:-invalid}
      EMAIL_SERVER: ${EMAIL_SERVER:-invalid}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS:-invalid}
      EMAIL_USER: ${EMAIL_USER:-invalid}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD:-invalid}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-invalid}
    depends_on:
      - "db"