default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default